# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a900c8439fcab5bfbbbb17f6ee50325d2d7d0ec0bd227c5032c66c6e8ec3d21da0f4ddb1859f0705d15085048c9c5b9170d603beefa380ace7797d0dd15f70

test:
  secret_key_base: 05f6431ac8776f6ac7ea9fca283cbbec995c23d8337a6a201ae526073448e3d40026b18c0d4b814141e1a3dae5d7b6bf4baea803a4802387f1742c4921f25aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
